### ISSUE TITLE
Soundfile.loop() only plays once

### ISSUE THREAD

**Issue by benfry** [processing/processing-sound-archive#58]
Reported here: https://github.com/processing/processing/issues/4081

**Comment by sjernigan** [comment]
Sorry, reported in the wrong repo.  I think this is a duplicate of
https://github.com/processing/processing-sound/issues/55

**Comment by sjernigan** [comment]
reproduced working with mono track, you can close this issue

**Comment by sunwangshu** [comment]
I have the same problem with stereo file using processing 3.0.1. Whichever stereo file I tried the loop() didn't work. Only mono files in the examples worked fine. I tried changing the ok mono files to stereo and the problem happen as well. So I guess the reason is difference of mono and stereo like you mentioned.
